### PR TITLE
Change2

### PR DESCRIPTION
**Pull request by gkoz**

### CODE REVIEW

**Comment by gkoz** [comment]
@homu-g try

**Comment by homu-g** [comment]
:hourglass: Trying commit cd3b88e with merge 793b51a...

**Comment by homu-g** [comment]
:sunny: Test successful - [status-appveyor](https://ci.appveyor.com/project/gkoz/homu-test/build/1.0.21), [status-travis](https://travis-ci.org/gkoz/homu-test/builds/126453037)

**Comment by gkoz** [comment]
@homu-g r+

**Comment by homu-g** [comment]
:pushpin: Commit cd3b88e has been approved by `gkoz`

**Comment by gkoz** [comment]
@homu-g retry

**Comment by homu-g** [comment]
:hourglass: Testing commit cd3b88e with merge 05fc1b1...

**Comment by homu-g** [comment]
:sunny: Test successful - [status-appveyor](https://ci.appveyor.com/project/gkoz/homu-test/build/1.0.23), [status-travis](https://travis-ci.org/gkoz/homu-test/builds/126457257)

**Pull request merged**
